import { 
  Building, 
  Users, 
  Users2,
  User,
  UserCircle,
  Package, 
  BarChart3, 
  FileText, 
  Handshake,
  DollarSign,
  Calendar,
  Truck,
  ShoppingCart,
  Warehouse,
  Box,
  ClipboardList,
  MessageSquare,
  UserCog,
  MapPin,
  FileSpreadsheet,
  Percent,
  Gauge,
  BookOpen,
  CreditCard,
  Minus,
  Plus,
  PackagePlus,
  PackageMinus,
  Cog,
  Store,
  Zap,
  Clock,
  Factory,
  ClipboardCheck,
  CalendarClock,
  Database,
  HelpCircle,
  Heart,
  Key,
  LogOut,
  Scale,
  LucideIcon
} from 'lucide-react';

export interface AppTile {
  name: string;
  icon: LucideIcon;
  color: string;
  description: string;
  path: string | null;
}

export const defaultApps: AppTile[] = [
  { name: 'Dashboard', icon: BarChart3, color: 'text-blue-500', description: 'Home dashboard', path: '/dashboard' },
  { name: 'Accounting', icon: Scale, color: 'text-emerald-600', description: 'Accounts, ledgers & inventory financials', path: '/accounting' },
  { name: 'Go', icon: Zap, color: 'text-yellow-500', description: 'Mobile work execution', path: '/go' },
  { name: 'POS', icon: Store, color: 'text-pink-500', description: 'Point of sale', path: '/pos' },
  { name: 'Cockpit', icon: Gauge, color: 'text-orange-500', description: 'Location dashboard', path: '/cockpit' },
  { name: 'Planning', icon: CalendarClock, color: 'text-violet-500', description: 'Demand planning', path: '/planning' },
  { name: 'Agreements', icon: Handshake, color: 'text-teal-500', description: 'Contracts & agreements', path: '/agreements' },
  { name: 'Sales Orders', icon: DollarSign, color: 'text-emerald-500', description: 'Customer orders', path: '/sales-orders' },
  { name: 'Inventory', icon: Warehouse, color: 'text-blue-500', description: 'Stock management', path: '/inventory' },
  { name: 'Bill of Materials', icon: ClipboardCheck, color: 'text-amber-500', description: 'Product recipes', path: '/bill-of-materials' },
  { name: 'Production', icon: Factory, color: 'text-indigo-500', description: 'Production orders', path: '/production' },
  { name: 'Goods Receipts', icon: PackagePlus, color: 'text-emerald-500', description: 'Receive inventory', path: '/goods-receipts' },
  { name: 'Goods Issues', icon: PackageMinus, color: 'text-orange-500', description: 'Issue inventory', path: '/goods-issues' },
  { name: 'Locations', icon: MapPin, color: 'text-green-500', description: 'Warehouses & stores', path: '/locations' },
  { name: 'Vendors', icon: Building, color: 'text-red-500', description: 'Suppliers & partners', path: '/vendors' },
  { name: 'Customers', icon: Users, color: 'text-violet-500', description: 'CRM & contacts', path: '/customers' },
  { name: 'Products', icon: Package, color: 'text-amber-500', description: 'Product catalog', path: '/products' },
  { name: 'Analytics', icon: BarChart3, color: 'text-pink-500', description: 'Reports & insights', path: '/analytics' },
  { name: 'Invoices', icon: FileText, color: 'text-cyan-500', description: 'Billing & payments', path: '/invoices' },
  { name: 'Credit Memos', icon: Minus, color: 'text-green-500', description: 'Account credits', path: '/credit-memos' },
  { name: 'Debit Memos', icon: Plus, color: 'text-red-500', description: 'Account debits', path: '/debit-memos' },
  { name: 'Accounts', icon: CreditCard, color: 'text-indigo-500', description: 'Customer & vendor accounts', path: '/accounts' },
  { name: 'Ledgers', icon: BookOpen, color: 'text-stone-500', description: 'Financial ledgers', path: '/ledgers' },
  { name: 'Rates', icon: Percent, color: 'text-yellow-500', description: 'Tax rates', path: '/rates' },
  { name: 'Orders', icon: ShoppingCart, color: 'text-orange-500', description: 'Vendor orders', path: '/orders' },
  { name: 'Requisitions', icon: FileSpreadsheet, color: 'text-sky-500', description: 'Purchase requests', path: '/requisitions' },
  { name: 'Deliveries', icon: Truck, color: 'text-teal-500', description: 'Logistics & delivery', path: '/deliveries' },
  { name: 'HR', icon: Heart, color: 'text-rose-500', description: 'Human resources', path: '/hr' },
  { name: 'Employees', icon: User, color: 'text-blue-500', description: 'Staff directory', path: '/employees' },
  { name: 'Time Clock', icon: Clock, color: 'text-cyan-500', description: 'Clock in/out', path: '/time-clock' },
  { name: 'Teams', icon: Users2, color: 'text-teal-500', description: 'Team management', path: '/teams' },
  { name: 'Calendar', icon: Calendar, color: 'text-indigo-500', description: 'Events & scheduling', path: '/calendar' },
  { name: 'Me', icon: UserCircle, color: 'text-sky-500', description: 'My profile & time off', path: '/me' },
  { name: 'Tasks', icon: ClipboardList, color: 'text-rose-500', description: 'To-dos & projects', path: '/tasks' },
  { name: 'Messages', icon: MessageSquare, color: 'text-lime-500', description: 'Team communication', path: '/messages' },
  { name: 'Users', icon: UserCog, color: 'text-purple-500', description: 'Team & access control', path: '/users' },
  { name: 'Configuration', icon: Cog, color: 'text-emerald-500', description: 'System & company settings', path: '/configuration' },
  { name: 'Data Explorer', icon: Database, color: 'text-cyan-500', description: 'Browse database tables', path: '/data-explorer' },
  { name: 'Transportation', icon: Truck, color: 'text-amber-500', description: 'Carriers & logistics', path: '/transportation' },
  { name: 'Assignments', icon: Users, color: 'text-violet-500', description: 'Vendor & source assignments', path: '/assignments' },
  { name: 'Developers', icon: Key, color: 'text-amber-500', description: 'API keys & webhooks', path: '/developers' },
  { name: 'Help', icon: HelpCircle, color: 'text-blue-500', description: 'Documentation & guides', path: '/help' },
  { name: 'Logout', icon: LogOut, color: 'text-destructive', description: 'Sign out of your account', path: null },
];
