import { EntityConfig } from "./types";

export const entities: EntityConfig[] = [
  {
    name: "Products",
    table: "products",
    fields: [
      { key: "product_id", label: "Product ID", type: "string" },
      { key: "name", label: "Name", type: "string" },
      { key: "description", label: "Description", type: "string" },
      { key: "category", label: "Category", type: "string" },
      { key: "sku", label: "SKU", type: "string" },
      { key: "upc", label: "UPC", type: "string" },
      { key: "price", label: "Price", type: "number" },
      { key: "cost", label: "Cost", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
      { key: "created_at", label: "Created At", type: "date" },
    ],
  },
  {
    name: "Inventory",
    table: "inventory",
    fields: [
      { key: "id", label: "ID", type: "string" },
      { key: "product_id", label: "Product ID", type: "string" },
      { key: "location_id", label: "Location ID", type: "string" },
      { key: "bin_id", label: "Bin ID", type: "string" },
      { key: "quantity", label: "Quantity", type: "number" },
      { key: "min_quantity", label: "Min Quantity", type: "number" },
      { key: "max_quantity", label: "Max Quantity", type: "number" },
      { key: "updated_at", label: "Updated At", type: "date" },
    ],
  },
  {
    name: "Product Safety Stock",
    table: "product_safety_stock",
    fields: [
      { key: "id", label: "ID", type: "string" },
      { key: "product_id", label: "Product ID", type: "string" },
      { key: "location_id", label: "Location ID", type: "string" },
      { key: "safety_stock_quantity", label: "Safety Stock Qty", type: "number" },
      { key: "created_at", label: "Created At", type: "date" },
    ],
  },
  {
    name: "Purchase Orders",
    table: "purchase_orders",
    fields: [
      { key: "order_id", label: "Order ID", type: "string" },
      { key: "vendor_id", label: "Vendor ID", type: "string" },
      { key: "location_id", label: "Location ID", type: "string" },
      { key: "status", label: "Status", type: "string" },
      { key: "total_amount", label: "Total Amount", type: "number" },
      { key: "order_date", label: "Order Date", type: "date" },
      { key: "expected_date", label: "Expected Date", type: "date" },
      { key: "created_at", label: "Created At", type: "date" },
    ],
  },
  {
    name: "Sales Orders",
    table: "sales_orders",
    fields: [
      { key: "order_id", label: "Order ID", type: "string" },
      { key: "customer_id", label: "Customer ID", type: "string" },
      { key: "location_id", label: "Location ID", type: "string" },
      { key: "status", label: "Status", type: "string" },
      { key: "total_amount", label: "Total Amount", type: "number" },
      { key: "order_date", label: "Order Date", type: "date" },
      { key: "created_at", label: "Created At", type: "date" },
    ],
  },
  {
    name: "Vendors",
    table: "vendors",
    fields: [
      { key: "vendor_id", label: "Vendor ID", type: "string" },
      { key: "name", label: "Name", type: "string" },
      { key: "contact_name", label: "Contact", type: "string" },
      { key: "email", label: "Email", type: "string" },
      { key: "phone", label: "Phone", type: "string" },
      { key: "city", label: "City", type: "string" },
      { key: "state", label: "State", type: "string" },
      { key: "is_active", label: "Active", type: "boolean" },
      { key: "created_at", label: "Created At", type: "date" },
    ],
  },
  {
    name: "Customers",
    table: "customers",
    fields: [
      { key: "customer_id", label: "Customer ID", type: "string" },
      { key: "name", label: "Name", type: "string" },
      { key: "contact_name", label: "Contact", type: "string" },
      { key: "email", label: "Email", type: "string" },
      { key: "phone", label: "Phone", type: "string" },
      { key: "city", label: "City", type: "string" },
      { key: "state", label: "State", type: "string" },
      { key: "type", label: "Type", type: "string" },
      { key: "created_at", label: "Created At", type: "date" },
    ],
  },
  {
    name: "Requisitions",
    table: "requisitions",
    fields: [
      { key: "requisition_id", label: "Requisition ID", type: "string" },
      { key: "vendor_id", label: "Vendor ID", type: "string" },
      { key: "location_id", label: "Location ID", type: "string" },
      { key: "status", label: "Status", type: "string" },
      { key: "total_amount", label: "Total Amount", type: "number" },
      { key: "created_at", label: "Created At", type: "date" },
    ],
  },
  {
    name: "Employees",
    table: "employees",
    fields: [
      { key: "employee_id", label: "Employee ID", type: "string" },
      { key: "first_name", label: "First Name", type: "string" },
      { key: "last_name", label: "Last Name", type: "string" },
      { key: "email", label: "Email", type: "string" },
      { key: "department", label: "Department", type: "string" },
      { key: "job_title", label: "Job Title", type: "string" },
      { key: "status", label: "Status", type: "string" },
      { key: "hire_date", label: "Hire Date", type: "date" },
    ],
  },
  {
    name: "Locations",
    table: "locations",
    fields: [
      { key: "location_id", label: "Location ID", type: "string" },
      { key: "name", label: "Name", type: "string" },
      { key: "type", label: "Type", type: "string" },
      { key: "city", label: "City", type: "string" },
      { key: "state", label: "State", type: "string" },
      { key: "country", label: "Country", type: "string" },
      { key: "created_at", label: "Created At", type: "date" },
    ],
  },
  {
    name: "Invoices",
    table: "invoices",
    fields: [
      { key: "invoice_number", label: "Invoice #", type: "string" },
      { key: "account_id", label: "Account ID", type: "string" },
      { key: "status", label: "Status", type: "string" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "invoice_date", label: "Invoice Date", type: "date" },
      { key: "due_date", label: "Due Date", type: "date" },
    ],
  },
];
